### ISSUE TITLE
Roadmap to a 2.0 release

### ISSUE THREAD

**Issue by achow101** [bitcoin-core/HWI#382]
There are bunch of things that I'd like to overhaul to make the code cleaner, easier to understand, and easier to use. Although the plan is to make internal changes, some changes will result in breaking the public API. As we (are attempting to) follow semver, that will require a major version bump to 2.0.0. The goal of these changes is to remove several of the hacks that we use, unify path, key origin, xpub, and descriptor handling, and be more pythonic with errors.

Here's the todo list:
- [x] Introduce `KeyOriginInfo` (done in #374)and unify all key origin handling to use it
- [x] Unify all xpub handling to use `ExtendedKey` rather than the ad hoc stuff we do now
- [x] Redo descriptors more similarly to Core and less hacky.
- [x] Unify how we treat fingerprints. Currently this is ad hoc and is a mix of int, hex string, and bytes.
- [x] Split up `displayaddress` to have multisig and descriptor variants. This command (and the function that it calls) is getting to bulky with mutually exclusive arguments
- [x] Raise exceptions instead of returning error dicts
- [x] Type check everything (except the vendor libraries)
- [x] Document everything with docstrings, write more usage docs, and host it all somewhere. I have been experimenting with using sphinx in a [branch in my repo](https://github.com/achow101/hardware-wallet-interface/tree/sphinx-docs) and have the docs it generates on [readthedocs.io](https://hardware-wallet-interface.readthedocs.io/en/latest/)
- [x] Specify a new device inclusion policy

In the interim, I would also like to get the Bitbox02 stuff merged and then release that as a 1.2. The next release after that should be the 2.0.

**Comment by instagibbs** [comment]
Mind if we scope this down a bit to API-breaking changes only for triage purposes?

Only ones I can see left is fingerprint treatement and exception raising.

Rest are "nice to have" and can be done in a follow-up release.

**Comment by achow101** [comment]
> Only ones I can see left is fingerprint treatement and exception raising.

These are fairly small anyways. I've already done a lot of exception raising work within the device implementations already. The fingerprint stuff shouldn't be that complicated to do either.

***

Type checking is already done in #456, so I think we should have it for 2.0.

It'd be nice to have docs for the API breaks though. I have started working on those and we can just get some prelim docs.

**Comment by achow101** [comment]
I think we also still need do a bit of refactoring and solidifying the public api. For example, it seems like `serializations.py` should be split up and some things (e.g. `base58.py` and `bech32.py`) should be made private.

**Comment by instagibbs** [comment]
Ok as long as we can efficiently get those in, dragging another month seems unnecessary.

**Comment by achow101** [comment]
How about we set a feature freeze for March 15th?

**Comment by instagibbs** [comment]
SGTM

**Comment by instagibbs** [comment]
Looks like we're down to documentation and inclusion policy? Latter might require some discussion.

**Comment by prusnak** [comment]
> Looks like we're down to documentation and inclusion policy? Latter might require some discussion.

Let's also discuss exclusion policy while discussing inclusion policy - example https://github.com/bitcoin-core/HWI/issues/386

**Comment by achow101** [comment]
I've updated the docs branch to be based on master. There are still a few things I would like to document before opening a pr.

In terms of an inclusion policy:
* As much open source firmware as possible
  * No closed source devices
  * Devices may have closed source firmware components if required to under a NDA (i.e. secure element with NDA)
* Publicly documented communication protocol
  * Preferably with a Python library implementing said protocol
  * Library implementing protocol can be counted as "publicly documented"
* Either a device simulator is available, or there is a promise to provide support and updates
  * Preferably have both, but if the device is something that we implemented, then there needs to be a simulator/emulator so that tests can be run
  * If the vendor wants it implemented, then they need to promise to provide support for it
    * If there are continuous issues with the device and the vendor has failed to provide support and updates, then we will remove the device
 
For an exclusion policy, I'm not sure. Maybe something like:
* If we are supporting it without vendor assistance, we may drop it if continued support becomes too onerous
* After the device is no longer sold and maintained by the vendor
  * Drop support if keeping it becomes to onerous
  * Drop support if the new vulnerabilities and security issues are discovered that are not fixed due to the device no longer being supported by the vendor

**Comment by instagibbs** [comment]
There's something to be said about dropping a device when it's no longer receiving security updates. The user should switch devices imo, and they can always run an older binary/release.

**Comment by instagibbs** [comment]
devices should probably also have a screen: https://github.com/bitcoin-core/HWI/issues/299

**Comment by achow101** [comment]
Once more thing that we should probably do is implement PSBT2. Luckily it shouldn't be too hard to do that.

**Comment by benma** [comment]
What does PSBT2 refer to?

> How about we set a feature freeze for March 15th? Or is that too long?

I'd appreciate a quicker release very much. BB02 users keep asking about multisig in Specter etc., which is waiting for the next HWI release.

**Comment by achow101** [comment]
> What does PSBT2 refer to?

[BIP 370](https://github.com/bitcoin/bips/pull/1059). On second thought, we don't need to have PSBTv2 for 2.0. Implementing it wouldn't be an API breaking change, not to mention that the BIP isn't even merged into the bips repo yet. So I think it will be fine to push that to a future release. I'll open a separate issue to track it.

**Comment by instagibbs** [comment]
No need to delay a release provided we have checked off the todos. We're almost there :)

**Comment by achow101** [comment]
All of the major things I wanted done for this release have been merged. There are a few issues that I want to fix and have been added to the [2.0.0 milestone](https://github.com/bitcoin-core/HWI/milestone/3). I expect that I will make an rc next week, however the current deadline remains March 15th.

**Comment by instagibbs** [comment]
So if RC ends up looking good, print a release, if not, allow API changes before March 15?

**Comment by achow101** [comment]
> So if RC ends up looking good, print a release, if not, allow API changes before March 15?

Yep

**Comment by achow101** [comment]
HWI 2.0.0-rc.2 is now available for testing (I screwed up rc1 so we're going to skip that).

**Comment by instagibbs** [comment]
Looks like we're on feature freeze, so only bugfixes from here on out
