### ISSUE TITLE
TODO for 1.0 release

### ISSUE THREAD

**Issue by achow101** [bitcoin-core/HWI#91]
At some point I would like to start doing proper versioning of HWI and release it as both a library and executable script on PyPi. The following need to be done before I feel comfortable doing this:

- [x] Separate `process_commands` from `commands.py` and have the functions in `commands.py` take actual arguments
- [x] Handle all possible errors so that no backtraces are printed
- [x] Remove any interactiivty and command line prompts (except for `--debug`). The only thing that should be output is the result. (This may not be possible for Trezor and Keepkey, see #83)
- [x] Have all devices have implementations for all commands. No `NotImplementedError`s
- [x] Tests for all commands, especially transaction signing (incl. multisig)
- [x] Manual test for ledger
- [x] ~~Manual~~ Automated test for bitbox
- [x] Automated test for keepkey
- [x] Move to bitcoin-core org
- [x] Deterministic binary and archive builds
- [x] `--version` option
- [x] Whatever else is listed in the 1.0 milestone

**Comment by instagibbs** [comment]
Just food for thought: It might also make sense to move this repo into some organization, and establish contributor guidelines/review process going forward.

**Comment by achow101** [comment]
Since the main goal of this project is to get hardware wallet support into Core, we could see if this can be moved under the bitcoin-core org.

**Comment by instagibbs** [comment]
https://github.com/bitcoin-core/HWI/pull/121 resolves "* Deterministic binary and archive builds" I presume

**Comment by instagibbs** [comment]
I think "* Tests for all commands, especially transaction signing (incl. multisig)" has been covered. Multisig tests have been merged.

**Comment by instagibbs** [comment]
is there a tracking issue for `--version`?

**Comment by Sjors** [comment]
I'd also like #117 in that release as it would allow for library based testing of https://github.com/bitcoin/bitcoin/pull/14912. Although probably I'll need message signing commands too, to double check the import.

**Comment by instagibbs** [comment]
With the -cli limit on transaction sizes(noted in https://github.com/bitcoin-core/HWI/pull/125) I think we should add https://github.com/bitcoin-core/HWI/issues/46 to the list so a -cli user can side-step this limitation.

**Comment by achow101** [comment]
Everything tagged has been merged. I'll tag and publish the release tomorrow.
